openapi: 3.0.0
info:
  title: API Name
  version: '1.0'
  description: API Description
servers:
  - url: 'http://localhost:3000'
paths:
  /procedures/bestowal:
    post:
      summary: Create Procedure
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ProcedureId:
                    type: string
                  ProcedureNumber:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  ValidationErrors:
                    type:
                      - string
                      - array
                    items:
                      type: object
                      properties:
                        ErrorNumber:
                          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                LandType:
                  type: string
                LandName:
                  type: string
                LandId:
                  type: string
              required:
                - LandType
                - LandName
                - LandId
      description: Endpoint descriion for testing
      operationId: create op
    parameters: []
  /properties/lands/types:
    get:
      summary: get
      tags: []
      responses: {}
  /landtypes:
    get:
      summary: Get Land Types
      tags:
        - tag1
      responses: {}
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
